# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseCoreDataCursoBF348' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseCoreDataCursoBF348

pod 'FirebaseAuth'

end
